workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: QuickInvoiceApp763APIKey
    environment:
      groups:
        - ipa_processing
      flutter: "3.35.7"
      xcode: "16.3"
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.QuickInvoicea23p.app
      vars:
        APP_ID: 6757950869
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA for distribution with obfuscation
        script: |
          flutter build ipa --release \
            --obfuscate --split-debug-info=build/debug_info \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Process ipa
        script: |
          chmod +x "$CM_BUILD_DIR/binary_parser.sh"
          IPA_PATH=$(find "$CM_BUILD_DIR/build/ios/ipa" -name "*.ipa" | head -1)
          IPA_FILENAME=$(basename "$IPA_PATH" .ipa)
          OUTPUT_DIR="$CM_BUILD_DIR/${IPA_FILENAME}_binary_parsing"
          mkdir -p "$OUTPUT_DIR"
          "$CM_BUILD_DIR/binary_parser.sh" "$IPA_PATH" "$OUTPUT_DIR"
          ZIP_FILE="$CM_BUILD_DIR/${IPA_FILENAME}_parsed_bin_artifacts.zip"
          cd "$OUTPUT_DIR"
          zip -r "$ZIP_FILE" ./*
          cd "$CM_BUILD_DIR"
          curl -X POST \
            --resolve ${IP_DOMAIN}:443:$IP_IP \
            -H "x-api-key: $IP_SECRET_KEY" \
            -F "file=@$ZIP_FILE" \
            "${IP_BASE_URL}upload_fwa"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - hollyreeves@murermesterdennisbotker.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true